#!/usr/bin/env ruby

begin
  require 'rstfilter'
rescue LoadError
  $:.unshift File.expand_path('../lib', __dir__)
  require 'rstfilter'
end

RstFilter::Config.set_default! ARGV
ARGV.each{|name|
  f = RstFilter::Exec.new name
  f.process
}
